### ISSUE TITLE
Custom Products cannot be saved

### ISSUE THREAD

**Issue by falkvw** [FriendsOfShopware/FroshPlatformShareBasket#10]
## Actual behaviour

    We are using the Shopware Plugin Custom Products (https://docs.shopware.com/de/shopware-6-de/erweiterungen/customproducts?category=shopware-6-de/erweiterungen) . When one of those configurable products is in the cart, the cart cannot be saved. 

## Expected behaviour

    Save carts including configurable products.

## Environment

    - Shopware 6.3.4
    - Warenkorb teilen Plugin 0.1.3
    - PHP 7.4

## Steps to reproduce

1. Install Custom products Plugin
2. Configure custom product
3. add custom product to cart
4. try to save cart

**Comment by stefanpoensgen** [comment]
I'm currently looking into this. Will implement it in near future.
