### ISSUE TITLE
"Payment method is blocked for the current cart"

### ISSUE THREAD

**Issue by wexorda** [FriendsOfShopware/FroshPlatformShareBasket#13]
### PHP Version

7.4.22

### Shopware Version

6.4.2.1

### Actual behaviour

When clicking a link to a cart, I get redirected to the cart, as expected, but will have an error message saying my default payment method(card) is blocked for the current cart, despite it always being allowed. If I refresh, the message will disappear, and I am also able to use the payment method with no issues.

### Expected behaviour

The cart loads, displaying no errors, unless there actually is one.

### Steps to Reproduce?

Have multiple payment methods, generate link, and use it to go to cart.

**Comment by shyim** [comment]
Happens this on any cart? Do we need to do something special?

**Comment by wexorda** [comment]
Sorry for the delay,
yes, in my tests, it happens for every cart, and I have been unable to make it not happen
