### ISSUE TITLE
Vouchers Share Basket

### ISSUE THREAD

**Issue by kaskowski** [FriendsOfShopware/FroshPlatformShareBasket#14]
### PHP Version

PHP 7.4

### Shopware Version

6.4.7.0

### Actual behaviour

If you add voucher codes to the basket you're receive failure notification on open it. If you delete the promotion code line from `frosh_share_basket_line_item` and open the basket is all okay.

### Expected behaviour

Fix to add vouchers in to the sharing basket and customers could open it.

### Steps to Reproduce?

Add Articles and a general promotion code to the basket, share the basket and open it. You see and empty basket. Sometimes you can open the basket with click one the basket symbol and you can only see the article without any promotion code. On some platforms you became an error notifcation.

**Comment by ChrisWe** [comment]
@kaskowski @shyim Do you have a solution to this issue or maybe a hint how to add discounts? 
I would like to fix this but im not that familiar with shopware 6 yet. I can't find the cart entry for the voucher in the database and i assume thats the underlying problem here.

**Comment by DannyDan** [comment]
I dont know but I cant reproduce the issue. The Discount is also in the cart when opening the cart via the direct url.
