### ISSUE TITLE
Custom Products mit im Warenkorb speichern

### ISSUE THREAD

**Issue by TCunert** [FriendsOfShopware/FroshPlatformShareBasket#15]
### Please describe the feature you would like to see implemented.

Hallo,

das Plugin funktioniert super.

Wäre es noch möglich das wenn ich Custom Products im Einsatz habe diese auch mit im Warenkorb gespeichert werden können.
Kontakt gern auch per Mail tilo.cunert@gmx.de

Vielen Dank.

**Comment by tinect** [comment]
Duplicates #10
