### ISSUE TITLE
adding compatibility to plugin 

### ISSUE THREAD

**Issue by turi66** [FriendsOfShopware/FroshPlatformShareBasket#19]
### Please describe the feature you would like to see implemented.

So the plugin is very well, but unfortunately it saves basket not correct. We use the plugin "Artikel Konfigurator für Sets / Bundles" from digitvision, which extends the Shopware products. I think it is unknown for your plugin. Would be great if you can add compatibbility.

You can test it in our shop here:
https://shop.led-studien.de/zubehoer/aluprofile/2m-led-micro-profil-pl1/al21bund

Thanks a lot.

**Comment by stefanpoensgen** [comment]
I'm currently not planning to integrate 3rd party plugins.
