### ISSUE TITLE
Share cart does not output URL

### ISSUE THREAD

**Issue by Transwatt** [FriendsOfShopware/FroshPlatformShareBasket#30]
### PHP Version

8.1

### Shopware Version

6.5.6.1

### Plugin Version

1.1.6 

### Actual behaviour

Share cart does not output URL

### Expected behaviour

Share cart does not output URL

### Steps to Reproduce?

Install, activate and check plugin...

**Comment by stefanpoensgen** [comment]
Please check all your plugins and customizations to the template. I currently cannot replicate any erroneous behavior.

**Comment by Transwatt** [comment]
Uninstalling the addon, including the addon data and reinstalling it fixed the problem
