### ISSUE TITLE
Plugin can't handle multiple saleschannels with same products

### ISSUE THREAD

**Issue by vicotec** [FriendsOfShopware/FroshPlatformShareBasket#34]
### PHP Version

8.1

### Shopware Version

6.5.7.3

### Plugin Version

1.1.6

### Actual behaviour

If you have multiple saleschannels with overlapping products, let's say SaleschannelA, SaleschannelB and ExampleProductA, and save the basket with 1 ExampleProductA in SaleschannelA, then you get a link to load the basket.
Then repeat the process for SaleschannelB. You don't get a link for the basket, but an empty input.

### Expected behaviour

Too recieve two links to load the basket for the different saleschannels.

### Steps to Reproduce?

See actual behaviour.

**Comment by vicotec** [comment]
I think i already tracked down, how to fix the issue, but I'm not certain.
In "ShareBasketService->prepareLineItems()" at the end the hash is formed like this:
`'hash' => sha1(serialize($lineItems)),`
If you change this part, too include the saleschannel like this
`'hash' => sha1(serialize($lineItems) . $salesChannelContext->getSalesChannel()->getId()),`
it seems to solve the problem.

**Comment by stefanpoensgen** [comment]
Sounds good. I'll look into it later.

**Comment by stefanpoensgen** [comment]
i tagged a new release 
https://github.com/FriendsOfShopware/FroshPlatformShareBasket/releases/tag/1.1.7
