### ISSUE TITLE
Styles Not Loading Correctly after deployment 

### ISSUE THREAD

**Issue by chihiro7793** [FriendsOfShopware/FroshPlatformShareBasket#36]
### Question

Hi,
I'm experiencing an issue that after deploying the plugin to my staging environment, the cart is saved correctly, but when I try to open the saved cart using the generated link, the styles and JavaScript are not being applied correctly. The styles and scripts load perfectly in my local development environment.

Environment Details
Shopware Version: 6.4.8.2
Plugin Version: 0.3.0
Hosting Environment: Maxcluster
Web Server: [Apache/Nginx]

The browser's developer tools show 404 errors for the following assets:
all.css
all.js

Could you please help me figure out where things go wrong?

**Comment by stefanpoensgen** [comment]
The issue likely stems from your deployment and build process. Involving someone with devops experience may help resolve this issue.
