### ISSUE TITLE
Compatibility with Neonlines Product Configurator plugin

### ISSUE THREAD

**Issue by nicoloma89** [FriendsOfShopware/FroshPlatformShareBasket#48]
### Please describe the feature you would like to see implemented.

Hallo, wir nutzen das Plugin von neonlines "Konfigurator, Produktkonfigurator".

Leider wird beim teilen des Warenkorbs, die konfiguration nicht mitgenommen.

**Comment by schneider-felix** [comment]
Hi @nicoloma89,

sadly we can not ensure that custom cart functionality provided by other plugins will automatically be compatible with our plugin. We do however provide events that can be used to save additional data for each line item. Using those events your shopware agency might be able to build a connection between the two plugins.
