### ISSUE TITLE
Tag 0.1.2

### ISSUE THREAD

**Issue by s-diez** [FriendsOfShopware/FroshPlatformShareBasket#6]
## Actual behaviour

All releases from the shopware plugin store are tagged and released on github except 0.1.2.

## Expected behaviour

Tag and Release for Version 0.1.2 exists.

## Environment

Irrelevant

## Steps to reproduce

- See List of released Versions in Github https://github.com/FriendsOfShopware/FroshPlatformShareBasket/releases
- 0.1.2 is missing

**Comment by shyim** [comment]
Sorry. Is released
