### ISSUE TITLE
Shopware 6.4 compat is not given due to missing shopware.config refactoring

### ISSUE THREAD

**Issue by MDSLKTR** [FriendsOfShopware/FroshPlatformShareBasket#9]
## Actual behaviour

6.4 compatibility is not given even though the requirements are marked in the composer.json

## Expected behaviour

shopware.config is replaced by config('key') and compat is given

## Environment
	Shopware 6.4.1.0
    Plugin version 0.2.0

## Steps to reproduce

Check src/Resources/views/storefront/utilities/frosh-share-basket.html.twig and see that the deprecated shopware.config is still used which is null since Shopware 6.4

**Comment by tinect** [comment]
Thank you! I fixed it with new release.
